package org.sarge.jove.control;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.sarge.jove.control.Event.AbstractEvent;

/**
 * An <i>axis event</i> describes an event generated by an axial controller such as the mouse wheel or a controller gauge.
 * @author Sarge
 */
public class AxisEvent extends AbstractEvent {
	private final float value;

	/**
	 * Constructor.
	 * @param type		Axis type
	 * @param src		Source
	 * @param value		Axis value
	 */
	public AxisEvent(Type type, Source src, float value) {
		super(type, src);
		this.value = value;
	}

	/**
	 * @return Axis value
	 */
	public float value() {
		return value;
	}

	@Override
	public String toString() {
		return new ToStringBuilder(this)
				.appendSuper(super.toString())
				.append(value)
				.build();
	}
}
