package org.sarge.jove.control;

/**
 * An <i>axis event</i> is generated by an axis device such as the mouse wheel or a joystick throttle.
 * @author Sarge
 */
public record AxisEvent(int value) implements Event {
}
