package org.sarge.jove.control;

import org.sarge.jove.control.Axis.AxisEvent;
import org.sarge.jove.control.Event.Source;
import org.sarge.lib.util.Check;

/**
 * An <i>axis</i> generates events for an axial controller such as the mouse wheel or a HOTAS gauge.
 * @author Sarge
 */
public interface Axis extends Source<AxisEvent> {
	/**
	 * @return Current axis position
	 */
	float value();

	/**
	 * An <i>axis handler</i> defines the signature for methods to bind to an axis.
	 */
	@FunctionalInterface
	interface Handler {
		/**
		 * Accepts an axis event.
		 * @param value Axis value
		 */
		void handle(float value);
	}

	/**
	 * An <i>axis event</i> describes an event generated by this axis.
	 */
	record AxisEvent(Axis axis, float value) implements Event {
		/**
		 * Constructor.
		 * @param axis		Axis
		 * @param value		Axis position
		 */
		public AxisEvent {
			Check.notNull(axis);
		}

		@Override
		public Object type() {
			return axis;
		}
	}
}
