package org.sarge.jove.control;

import java.util.Set;
import java.util.function.Consumer;

import org.sarge.jove.control.InputEvent.Type;

/**
 *
 * @author Sarge
 */
public interface Device {
	/**
	 * @return Device name
	 */
	String name();

	/**
	 * @return Event types generated by this device
	 */
	Set<Class<? extends Type>> types();

	/**
	 * Enables events of the given type from this device.
	 * @param type			Event type
	 * @param handler		Event handler
	 */
	void enable(Class<? extends Type> type, Consumer<InputEvent<?>> handler);

	/**
	 * Helper - Enables <b>all</b> events generated by the given device.
	 * @param dev			Device
	 * @param handler		Event handler
	 */
	static void enable(Device dev, Consumer<InputEvent<?>> handler) {
		for(final var type : dev.types()) {
			dev.enable(type, handler);
		}
	}
}
