package org.sarge.jove.control;

import java.util.Set;

import org.sarge.jove.control.InputEvent.Handler;
import org.sarge.jove.control.InputEvent.Type;

/**
 *
 * @author Sarge
 */
public interface Device {
	/**
	 * @return Device name
	 */
	String name();

	/**
	 * @return Event types generated by this device
	 */
	Set<Class<? extends Type>> types();

	/**
	 * Enables events of the given type from this device.
	 * @param type			Event type
	 * @param handler		Event handler
	 */
	void enable(Class<? extends Type> type, Handler<?> handler);
//	<T extends Type> void enable(Class<T> type, Handler<T> handler);

//	/**
//	 * Disables events of the given type.
//	 * @param type Event type
//	 */
//	void disable(Class<? extends Type> type);

	/**
	 * Helper - Enables <b>all</b> events generated by the given device.
	 * @param dev			Device
	 * @param handler		Event handler
	 */
	static void enable(Device dev, InputEvent.Handler handler) {
//		for(final var type : dev.types()) {
//			dev.enable(type, handler);
//		}
	}

//	void enable(Button type, Consumer<Button> handler);
}
