package org.sarge.jove.control;

import static java.util.stream.Collectors.joining;

import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.function.Consumer;
import java.util.function.Predicate;

/**
 * An <i>event</i> describes an input from the client.
 * <p>
 * An event is comprised of:
 * <ul>
 * <li>a <i>name</i> that identifies the event</li>
 * <li>a {@link Type} which describes the event category</li>
 * <li>the {@link Source} that generated the event</li>
 * </ul>
 * <p>
 * @author Sarge
 */
public interface Event {
	/**
	 * Event name delimiter.
	 */
	String DELIMITER = "-";

	/**
	 * Builds a delimited event name from the given tokens.
	 * @param tokens Name tokens
	 * @return Event name
	 */
	static String name(String... tokens) {
		return Arrays
				.stream(tokens)
				.filter(Predicate.not(String::isEmpty))
				.collect(joining(DELIMITER));
	}

	/**
	 * @return Type of event
	 */
	Type<?> type();

	/**
	 * TODO
	 * @param <T> Event type
	 */
	interface Type<T extends Event> {
		/**
		 * @return
		 */
		String name();

		/**
		 * @return Source of this type of event
		 */
		Source source();
	}

	/**
	 * An <i>event source</i> generates events.
	 */
	interface Source {
		/**
		 * @return Device
		 */
		Device device();

		/**
		 * @return Types of events generated by this source
		 */
		List<? extends Type<?>> types();

		/**
		 * Binds the given handler to this source.
		 * @param handler Event handler
		 */
		void bind(Consumer<Event> handler);

		/**
		 * Disables this source.
		 */
		void disable();
	}

	/**
	 * A <i>device</i> is comprised of a number of event sources.
	 */
	interface Device {
		/**
		 * @return Event sources
		 */
		Set<Source> sources();

		/**
		 * Closes this device.
		 */
		void close();
	}
}
