package org.sarge.jove.control;

import java.util.List;
import java.util.Set;

/**
 * An <i>input event</i> describes an event generated by a device.
 * @author Sarge
 */
public interface InputEvent {
	/**
	 * @return Type of this event
	 */
	Type type();

	/**
	 * An <i>event type</i> is the descriptor for an input event.
	 */
	interface Type {
		/**
		 * Delimiter for the string representation of an event.
		 */
		String DELIMITER = "-";

		/**
		 * @return Event name
		 */
		String name();
	}

	/**
	 * An <i>input event source</i> defines a generator of input events.
	 * @param <T> Type of event
	 */
	interface Source<T extends Type> {
		/**
		 * @return Events generated by this source
		 */
		List<T> types();

		/**
		 * Enables generation of events.
		 * @param handler Event handler
		 */
		void enable(Handler handler);

		/**
		 * Disables event generation.
		 */
		void disable();
	}

	/**
	 * A <i>device</i> is comprised of a group of event sources.
	 */
	interface Device {
		/**
		 * @return Device name
		 */
		String name();

		/**
		 * @return Event sources for this device
		 */
		Set<Source<?>> sources();
	}
}
