package org.sarge.jove.platform.vulkan.core;

import static java.util.stream.Collectors.joining;
import static org.apache.commons.lang3.StringUtils.removeEnd;
import static org.apache.commons.lang3.StringUtils.removeStart;
import static org.sarge.lib.util.Check.notNull;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import java.util.StringJoiner;
import java.util.function.Consumer;

import org.sarge.jove.common.IntegerEnumeration;
import org.sarge.jove.platform.vulkan.VkDebugUtilsMessageSeverityFlagEXT;
import org.sarge.jove.platform.vulkan.VkDebugUtilsMessageTypeFlagEXT;
import org.sarge.jove.platform.vulkan.VkDebugUtilsMessengerCallbackDataEXT;
import org.sarge.jove.platform.vulkan.VkDebugUtilsMessengerCreateInfoEXT;
import org.sarge.lib.util.Check;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;

/**
 * A <i>message</i> is a diagnostics report generated by Vulkan.
 * @author Sarge
 */
public record Message(VkDebugUtilsMessageSeverityFlagEXT severity, Collection<VkDebugUtilsMessageTypeFlagEXT> types, VkDebugUtilsMessengerCallbackDataEXT data) {
	/**
	 * Helper - Converts the given severity flag to a human-readable string.
	 * @param severity Message severity
	 * @return Severity string
	 */
	public static String toString(VkDebugUtilsMessageSeverityFlagEXT severity) {
		return clean(severity.name(), "SEVERITY");
	}

	/**
	 * Helper - Converts the given message type to a human-readable string.
	 * @param type Message type
	 * @return Message type string
	 */
	public static String toString(VkDebugUtilsMessageTypeFlagEXT type) {
		return clean(type.name(), "TYPE");
	}

	/**
	 * Helper - Strips the surrounding text from the given enumeration constant name.
	 * @param name Enumeration constant name
	 * @param type Type name
	 * @return Cleaned name
	 */
	private static String clean(String name, String type) {
		final String prefix = new StringBuilder()
				.append("VK_DEBUG_UTILS_MESSAGE_")
				.append(type)
				.append("_")
				.toString();

		return removeEnd(removeStart(name, prefix), "_BIT_EXT");
	}

	/**
	 * Constructor.
	 * @param severity		Severity
	 * @param types			Message type(s)
	 * @param data			Message data
	 */
	public Message {
		Check.notNull(severity);
		Check.notEmpty(types);
		Check.notNull(data);
	}

	/**
	 * Constructs a string representation of this message.
	 * <p>
	 * The message text is a colon-delimited string comprised of the following elements:
	 * <ul>
	 * <li>severity</li>
	 * <li>type(s)</li>
	 * <li>message identifier</li>
	 * <li>message text</li>
	 * </ul>
	 * Example:
	 * <code>ERROR:VALIDATION-GENERAL:1234:message</code>
	 * <p>
	 * @return Message text
	 */
	@Override
	public String toString() {
		final String compoundTypes = types.stream().map(Message::toString).collect(joining("-"));
		final StringJoiner str = new StringJoiner(":");
		str.add(toString(severity));
		str.add(compoundTypes);
		if(!data.pMessage.contains(data.pMessageIdName)) {
			str.add(data.pMessageIdName);
		}
		str.add(data.pMessage);
		return str.toString();
	}

	/**
	 * Builder for the descriptor for a message handler.
	 */
	public static class HandlerBuilder {
		/**
		 * Helper - Creates a diagnostics message handler with a default configuration.
		 * @return Default message handler
		 */
		public static VkDebugUtilsMessengerCreateInfoEXT create() {
			return new HandlerBuilder().init().build();
		}

		private final Set<VkDebugUtilsMessageSeverityFlagEXT> severity = new HashSet<>();
		private final Set<VkDebugUtilsMessageTypeFlagEXT> types = new HashSet<>();
		private Consumer<Message> consumer = System.err::println;

		/**
		 * Sets the message consumer (default dumps message to the error console).
		 * @param consumer Message consumer
		 */
		public HandlerBuilder consumer(Consumer<Message> consumer) {
			this.consumer = notNull(consumer);
			return this;
		}

		/**
		 * Adds a message severity to be reported by this handler.
		 * @param severity Message severity
		 */
		public HandlerBuilder severity(VkDebugUtilsMessageSeverityFlagEXT severity) {
			this.severity.add(notNull(severity));
			return this;
		}

		/**
		 * Adds a message type to be reported by this handler.
		 * @param type Message type
		 */
		public HandlerBuilder type(VkDebugUtilsMessageTypeFlagEXT type) {
			types.add(notNull(type));
			return this;
		}

		/**
		 * Convenience method - Initialises this builder to the following defaults:
		 * <ul>
		 * <li>warnings and higher</li>
		 * <li>general or validation message types</li>
		 * </ul>
		 */
		public HandlerBuilder init() {
			severity(VkDebugUtilsMessageSeverityFlagEXT.VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT);
			severity(VkDebugUtilsMessageSeverityFlagEXT.VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT);
			type(VkDebugUtilsMessageTypeFlagEXT.VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT);
			type(VkDebugUtilsMessageTypeFlagEXT.VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT);
			return this;
		}

		/**
		 * Message callback.
		 * TODO - has to be class? lambda?
		 */
		private static class HandlerCallback implements Callback {
			private final Consumer<Message> consumer;

			private HandlerCallback(Consumer<Message> consumer) {
				this.consumer = consumer;
			}

			@SuppressWarnings("unused")
			public boolean message(int severity, int type, VkDebugUtilsMessengerCallbackDataEXT pCallbackData, Pointer pUserData) {
				// Transform bit-masks to enumerations
				final VkDebugUtilsMessageSeverityFlagEXT severityEnum = IntegerEnumeration.map(VkDebugUtilsMessageSeverityFlagEXT.class, severity);
				final Collection<VkDebugUtilsMessageTypeFlagEXT> typesEnum = IntegerEnumeration.enumerate(VkDebugUtilsMessageTypeFlagEXT.class, type);

				// Create message wrapper
				final Message message = new Message(severityEnum, typesEnum, pCallbackData);

				// Delegate to handler
				consumer.accept(message);

				// Continue execution
				return false;
			}
		}

		/**
		 * Constructs the handler descriptor.
		 * @return New handler descriptor
		 * @throws IllegalArgumentException if the message severities or types is empty
		 */
		public VkDebugUtilsMessengerCreateInfoEXT build() {
			// Validate
			if(severity.isEmpty()) throw new IllegalArgumentException("No message severities specified");
			if(types.isEmpty()) throw new IllegalArgumentException("No message types specified");

			// Build descriptor
			final VkDebugUtilsMessengerCreateInfoEXT info = new VkDebugUtilsMessengerCreateInfoEXT();
			info.messageSeverity = IntegerEnumeration.mask(severity);
			info.messageType = IntegerEnumeration.mask(types);
			info.pfnUserCallback = new HandlerCallback(consumer);
			info.pUserData = null;

			return info;
		}
	}
}
