package org.sarge.jove.input;

/**
 * Handler for {@link InputEvent}s generated by {@link Device}s.
 * @author Sarge
 */
public interface InputEventHandler {
	/**
	 * Notifies a new input event.
	 * @param event Input event
	 */
	void handle( InputEvent event );
}
