package org.sarge.jove.input;

/**
 * Platform-specific device responsible for generating input events.
 * @author Sarge
 */
public interface Device {
	/**
	 * @return Input events generated by this device
	 */
	EventType[] getEventTypes();

	/**
	 * Starts this device.
	 * @param handler Event handler
	 */
	void start( InputEventHandler handler );

	/**
	 * Stops this device.
	 */
	void stop();
}
