package org.sarge.jove.platform.vulkan;

import com.sun.jna.Pointer;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;

/**
 * Mock implementation that exposes generated by-reference values for easy mocking.
 * @author Sarge
 */
public class MockReferenceFactory implements ReferenceFactory {
	public final IntByReference integer = new IntByReference(1);
	public final PointerByReference ptr = new PointerByReference(new Pointer(2));
	public final Pointer[] pointers = new Pointer[] {new Pointer(3)};

	@Override
	public IntByReference integer() {
		return integer;
	}

	@Override
	public PointerByReference pointer() {
		return ptr;
	}

	@Override
	public Pointer[] pointers(int num) {
		return pointers;
	}
}
